# Generated by Django 3.2.13 on 2023-05-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.BooleanField(),
        ),
    ]
