# Generated by Django 3.2.13 on 2023-05-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='cood_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cood_y',
            field=models.FloatField(null=True),
        ),
    ]
